//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndumentariaIntimaWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int ID_VENTA { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> CLIENTE { get; set; }
        public int PRODUCTO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
        public string TIPODEPAGO { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
